config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: redirect('blog')
  get 'blog' => 'articles#index', :status => 301

  get 'quotes/new'
  resources :quotes

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new',:as => 'sign_up'
  resources :sessions
  resources :users

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
    

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					  length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 	belongs_to :article
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :quote, presence: true
	validates :author, presence: true
end

app/models/user.rb
# Schema: User(username:string, password_digest:string)
class User < ActiveRecord::Base
	has_secure_password
	validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  		if @current_user and @current_user.username == "hyperbit"
  			@current_user
  		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.order("created_at DESC")
	end

	def new
		@article = Article.new
		if current_user
			render :action => 'new', :layout => false
		else
	    	redirect_to articles_path
    	end
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
		render 'show'
	end

	def edit
		@article = Article.find(params[:id])
		if current_user
    		render :action => 'edit', :layout => false
	    else
	    	redirect_to @article
    	end
	end

	def update
		@article = Article.find(params[:id])
	 
		if @article.update(article_params)
	    	redirect_to @article
		else
	    	render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if current_user
			@article.destroy
		end

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.create(comment_params)
	    redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
	 
	private
		def comment_params
	    	params.require(:comment).permit(:commenter, :body)
	    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quotes = Quote.all
	end

	def new
		@quote = Quote.new
		if current_user
			render :action => 'new', :layout => false
		else
			redirect_to articles_path
		end
	end

	def create
		@quote = Quote.new(quote_params)

		if @quote.save
			redirect_to quotes_path
		else
			render 'new'
		end
	end

	def edit
		@quote = Quote.find(params[:id])
		if current_user
    		render :action => 'edit', :layout => false
	    else
	    	redirect_to @article
    	end
	end

	def update
		@quote = Quote.find(params[:id])
	 
		if @quote.update(quote_params)
	    	redirect_to articles_path
		else
	    	render 'edit'
		end
	end

	def destroy
		@quote = Quote.find(params[:id])
		if current_user
			@quote.destroy
		end

		redirect_to quotes_path
	end

	private
		def quote_params
			params.require(:quote).permit(:quote, :author)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	render :action => "new", :layout => false
  end

  def create
  	user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to articles_path, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
		render :action => "new", :layout => false
  	end
  end

  def destroy
  		session[:user_id] = nil
  		redirect_to articles_path, :notice => "Logged out"
  end

end

app/controllers/truncate_html.rb
require File.join(File.dirname(__FILE__), 'truncate_html', 'version')
require File.join(File.dirname(__FILE__), 'truncate_html', 'html_truncator')
require File.join(File.dirname(__FILE__), 'truncate_html', 'html_string')
require File.join(File.dirname(__FILE__), 'truncate_html', 'configuration')
require File.join(File.dirname(__FILE__), 'app', 'helpers', 'truncate_html_helper')

TruncateHtml.configure do |config|
  config.length        = 100
  config.omission      = '...'
  config.word_boundary = /\S/
end


ActionController::Base.helper(TruncateHtmlHelper) if defined?(ActionController)

app/controllers/truncate_html/configuration.rb
module TruncateHtml
  class Configuration
    attr_accessor :length, :omission, :word_boundary, :break_token
  end

  class << self
    attr_accessor :configuration
  end

  def self.configure
    self.configuration ||= Configuration.new
    yield configuration
  end
end

app/controllers/truncate_html/html_string.rb
# encoding: utf-8
module TruncateHtml
  class HtmlString < String

    UNPAIRED_TAGS = %w(br hr img).freeze
    REGEX = /(?:<script.*>.*<\/script>)+|<\/?[^>]+>|[[[:alpha:]][0-9]\|`~!@#\$%^&*\(\)\-_\+=\[\]{}:;'²³§",\.\/?]+|\s+|[[:punct:]]/.freeze

    def initialize(original_html)
      super(original_html)
    end

    def html_tokens
      scan(REGEX).map do |token|
        HtmlString.new(
          token.gsub(
            /\n/,' ' #replace newline characters with a whitespace
          ).gsub(
            /\s+/, ' ' #clean out extra consecutive whitespace
          )
        )
      end
    end

    def html_tag?
      /<\/?[^>]+>/ === self && !html_comment?
    end

    def open_tag?
      /<(?!(?:#{UNPAIRED_TAGS.join('|')}|script|\/))[^>]+>/i === self
    end

    def html_comment?
      /<\s?!--.*-->/ === self
    end

    def matching_close_tag
      gsub(/<(\w+)\s?.*>/, '</\1>').strip
    end

  end
end

app/controllers/truncate_html/version.rb
module TruncateHtml
  VERSION = "0.9.2"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
    render :action => "new", :layout => false
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to new_session_path, :notice => "Signed up!"
  	else
  		render :action => "new", :layout => false
  	end
  end

  private
  	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		#render :action => "index", :layout => false
		redirect_to 'http://www.jcano.info', :status => 301
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/truncate_html_helper.rb
module TruncateHtmlHelper
	def truncate_html(html, options={})
		return '' if html.nil?
		html_string = TruncateHtml::HtmlString.new(html)
		TruncateHtml::HtmlTruncator.new(html_string, options).truncate.html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="article">
  <%= form_for @article do |f| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <script>
      CKEDITOR.replace( 'article_text' );
    </script>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<%= render "layouts/blankheader" %>
<%= render 'form' %>

<%= link_to 'Back', articles_path, :class => "button" %>
<%= render "layouts/blankfooter" %>

app/views/articles/index.html.erb
<div class="article">
  <% @articles.each do |article| %>
    <h1><%= link_to article.title, article_path(article) %></a></h1>
    <em class="timestamp"><%= article.created_at.strftime("%A, %B %d, %Y") %></em>
    <p>
    <%= truncate_html(article.text, word_boundary: false, length: 500) %>
    <%= link_to raw("<p><em>Continue reading <i class=\"fa fa-arrow-circle-o-right\"></i></em></p>"), article_path(article), :id => "continue", :class => "right" %>
    </p>
     
    <% if current_user %>
      <%= link_to 'Edit', edit_article_path(article) %>
      | <%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <hr>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render "layouts/blankheader" %>
<%= render 'form' %>

<%= link_to 'Back', articles_path, :class => "button" %>
<%= render "layouts/blankfooter" %>

app/views/articles/show.html.erb
<div class="article">
	
	<h1><%= @article.title %></h1>

	<em class="timestamp"><%= @article.created_at.strftime("%A, %B %d, %Y") %></em>

	<br />

	<%= link_to raw("<em><i class=\"fa fa-arrow-circle-o-left\"></i> Back</em>"), articles_path, :id => "continue" %>

	<p>
	  <%= simple_format(@article.text) %>
	</p>

	<% if current_user %>
		<%= link_to 'Back', articles_path, :class => "button" %>
		<%= link_to 'Edit', edit_article_path(@article), :class => "button" %>
		 <%= link_to 'Destroy', article_path(@article),
	                method: :delete, data: { confirm: 'Are you sure?' }, :class => "button alert" %>
	<% else %>
		<%= link_to raw("<p><em><i class=\"fa fa-arrow-circle-o-left\"></i> Back</em></p>"), articles_path, :id => "continue" %>
	<% end %>
</div>
<div>
	<hr>
	<div class="small-12 medium-7">
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
	<h3>Comments</h3>
	<%= render @article.comments %>

</div>

app/views/comments/_comment.html.erb
<% if not comment.created_at.blank? %>
<div class="comment">
	<strong><%= comment.commenter %></strong>
	<em class="time_ago"><%= time_ago_in_words(comment.created_at) %> ago</em>
	<div class="panel">
		<p>
	  	<%= comment.body %>
		</p>
	</div>

	<% if current_user %>
		<p>

			<%= link_to 'Destroy Comment', [comment.article, comment],
		               method: :delete,
		               data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>
<% else %>
	<div class="panel"></div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter, "Name" %>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/quotes/_form.html.erb
<div class="quote">
  <%= form_for @quote do |f| %>
    <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited
        this quote from being saved:</h2>
      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= f.label :quote %><br>
      <%= f.text_area :quote %>
    </p>
   
    <p>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/quotes/edit.html.erb
<h1>Editing article</h1>
<%= render "layouts/blankheader" %>
<%= render 'form' %>

<%= link_to 'Back', quotes_path, :class => "button" %>
<%= render "layouts/blankfooter" %>

app/views/quotes/index.html.erb
<div class="quote">
  <%= link_to "Back", articles_path, :class => "button" %>
  <% @quotes.each do |quote| %>
    <blockquote class="quote index" style="color:#000;">
      <i class="fa fa-quote-left"></i>
        <%= quote.quote %>
      <i class="fa fa-quote-right"></i><cite class="quote index" style="color:#FF3C1F;"><%= quote.author %></cite>
    </blockquote>
     
    <% if current_user %>
      <%= link_to 'Edit', edit_quote_path(quote) %>
      | <%= link_to 'Destroy', quote_path(quote),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <hr>
  <% end %>
</div>

app/views/quotes/new.html.erb
<h1>New Quote</h1>
<%= render "layouts/blankheader" %>
<%= render 'form' %>

<%= link_to 'Back', quotes_path, :class => "button" %>
<%= render "layouts/blankfooter" %>

app/views/users/new.html.erb
<%= render "layouts/blankheader" %>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

<%= render "layouts/blankfooter" %>