config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: redirect('blog')
  get 'blog' => 'articles#index', :status => 301

  get 'quotes/new'
  resources :quotes

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new',:as => 'sign_up'
  resources :sessions
  resources :users

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
    

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					  length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 	belongs_to :article
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :quote, presence: true
	validates :author, presence: true
end

app/models/user.rb
# Schema: User(username:string, password_digest:string)
class User < ActiveRecord::Base
	has_secure_password
	validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  		if @current_user and @current_user.username == "hyperbit"
  			@current_user
  		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.order("created_at DESC")
	end

	def new
		@article = Article.new
		if current_user
			render :action => 'new', :layout => false
		else
	    	redirect_to articles_path
    	end
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
		render 'show'
	end

	def edit
		@article = Article.find(params[:id])
		if current_user
    		render :action => 'edit', :layout => false
	    else
	    	redirect_to @article
    	end
	end

	def update
		@article = Article.find(params[:id])
	 
		if @article.update(article_params)
	    	redirect_to @article
		else
	    	render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		if current_user
			@article.destroy
		end

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.create(comment_params)
	    redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
	 
	private
		def comment_params
	    	params.require(:comment).permit(:commenter, :body)
	    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quotes = Quote.all
	end

	def new
		@quote = Quote.new
		if current_user
			render :action => 'new', :layout => false
		else
			redirect_to articles_path
		end
	end

	def create
		@quote = Quote.new(quote_params)

		if @quote.save
			redirect_to quotes_path
		else
			render 'new'
		end
	end

	def edit
		@quote = Quote.find(params[:id])
		if current_user
    		render :action => 'edit', :layout => false
	    else
	    	redirect_to @article
    	end
	end

	def update
		@quote = Quote.find(params[:id])
	 
		if @quote.update(quote_params)
	    	redirect_to articles_path
		else
	    	render 'edit'
		end
	end

	def destroy
		@quote = Quote.find(params[:id])
		if current_user
			@quote.destroy
		end

		redirect_to quotes_path
	end

	private
		def quote_params
			params.require(:quote).permit(:quote, :author)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	render :action => "new", :layout => false
  end

  def create
  	user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to articles_path, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
		render :action => "new", :layout => false
  	end
  end

  def destroy
  		session[:user_id] = nil
  		redirect_to articles_path, :notice => "Logged out"
  end

end

app/controllers/truncate_html.rb
require File.join(File.dirname(__FILE__), 'truncate_html', 'version')
require File.join(File.dirname(__FILE__), 'truncate_html', 'html_truncator')
require File.join(File.dirname(__FILE__), 'truncate_html', 'html_string')
require File.join(File.dirname(__FILE__), 'truncate_html', 'configuration')
require File.join(File.dirname(__FILE__), 'app', 'helpers', 'truncate_html_helper')

TruncateHtml.configure do |config|
  config.length        = 100
  config.omission      = '...'
  config.word_boundary = /\S/
end


ActionController::Base.helper(TruncateHtmlHelper) if defined?(ActionController)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
    render :action => "new", :layout => false
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to new_session_path, :notice => "Signed up!"
  	else
  		render :action => "new", :layout => false
  	end
  end

  private
  	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		#render :action => "index", :layout => false
		redirect_to 'http://www.jcano.info', :status => 301
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/truncate_html_helper.rb
module TruncateHtmlHelper
	def truncate_html(html, options={})
		return '' if html.nil?
		html_string = TruncateHtml::HtmlString.new(html)
		TruncateHtml::HtmlTruncator.new(html_string, options).truncate.html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_blankfooter.html.erb
	</div>

  </body>
</html>

app/views/layouts/_blankheader.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "hyperbit" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<div class="container small-12 columns">

		<!-- Main Content -->
		<div class="small-12 medium-8 medium-push-1 columns" style="padding-top:50px;">

app/views/layouts/_footer.html.erb
			</div>
			<!-- Sidenav -->
			<div class="medium-3 columns hide-for-small">
				<div data-magellan-expedition="fixed" class="sidenav">
					<%= image_tag("pixelface.png", :class => "thumbnail", :align => "middle") %>
					<ul id="sidenav" class="side-nav no-bullet">
						<li><a href="https://www.google.com/maps/place/South+San+Francisco,+CA/@37.7027382,-122.4509376,12z/data=!4m2!3m1!1s0x808f790543feecef:0xf83a7579e756335d" target="_blank"><i class="fa fa-location-arrow"></i> Bay Area, CA</a></li>
						<li><a href="http://github.com/hyperbit" target="_blank"><i class="fa fa-github"></i> hyperbit</a></li>
						<li><a href="mailto:jcano001@ucr.edu"><i class="fa fa-envelope-o"></i> jcano001@ucr.edu</a></li>
						<li><a href="https://portfolium.com/justincano"><i class="fa fa-file-powerpoint-o"></i> Portfolium</a></li>
						<li><a href="http://www.jcano.me/dl/JustinCanoCEResume.pdf" target="_blank"><i class="fa fa-file-text-o"></i> Resume</a></li>
						<% if current_user %>
							<li><%= link_to 'New article', new_article_path %></li>
							<li><%= link_to 'Add Quote', new_quote_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div><!-- END MAIN CONTENT -->

		<!-- Footer -->
		<div class="footer">
			<div class="row footer">
				<div class="show-for-medium-up">
					<div class="medium-3 columns">
						<div class="row">
							<div class="small-12 columns" align="center">
							Created by Justin Cano<br />with lots of <i class="fa fa-heart"></i> <br />
							<%= image_tag("heroku-icon.png", :alt => "Heroku") %>
							<%= image_tag("rails-icon.png", :alt => "Ruby on Rails") %><br />
							</div>
						</div>
					</div>
					<div class="medium-6 columns end">
						<div class="row">
							<div class="small-12 columns">
								<% if Quote.exists? %>
									<% random_quote = Quote.offset(rand(Quote.count)).first %>
									<blockquote class="quote">
								      <i class="fa fa-quote-left"></i>
								        <%= random_quote.quote %>
								      <i class="fa fa-quote-right"></i><cite class="quote"><%= random_quote.author %></cite>
								    </blockquote>
							    <% end %>
							</div>
						</div>
					</div>
				</div>

				<div class="show-for-small-only">
					<div class="row" style="padding-top:15px;">
						<div class="small-12 columns" align="center">
							Created by Justin Cano with lots of <i class="fa fa-heart"></i> <br />
							<i class="fa fa-envelope-o"></i> <a href="mailto:jcano001@ucr.edu">jcano001@ucr.edu</a><br />
							<i class="fa fa-file-text-o"></i> <a href="/JustinCanoCEResume.pdf" target="_blank">Resume</a><br />
							<%= image_tag("heroku-icon.png", :alt => "Heroku") %>
							<%= image_tag("rails-icon.png", :alt => "Ruby on Rails") %><br />
						</div>
					</div>
				</div>
			</div><!-- END ROW FOOTER-->
		</div><!-- END FOOTER -->


    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
    	var s = skrollr.init()
    </script>
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title><%= content_for?(:title) ? yield(:title) : "hyperbit" %></title>

		<link href='http://fonts.googleapis.com/css?family=Raleway:400,200|Roboto' rel='stylesheet' type='text/css'>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
		<script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<%= csrf_meta_tags %>
		</head>

	<body>

		<div class="row" style="padding:10px;">
			<span class="header show-for-medium-up"><h1>H Y P E R B I T <small>P R O J E C T S</small></h1></span>
			<span class="header show-for-small-only"><h1>H Y P E R B I T</h1></span>
			<h3 class="subheader show-for-medium-up">Justin Cano's Blog</h2>
			<h3 class="subheader show-for-small-only">Justin Cano's Project Blog</h2>
			<hr />
		</div>

		<!-- Main Content -->
		<div class="row">
			<div class="small-12 medium-9 columns content">

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
    <%= yield %>
<%= render "layouts/footer" %>

app/views/layouts/footer.html.erb
</div>

</body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html ng-app="hyperbit">
<head>
  <title>Hyperbit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div ng-view>